name: Functions - main branch

on:
  push:
    branches:
      - 'main'

jobs:
  add-entry-function:
    name: Add Entry Function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd functions/add-entry-function
          mvn -B clean verify

      - name: Publish results to SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd functions/add-entry-function
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar -P sonar -Dsonar.login=${{ secrets.ADD_ENTRY_SONAR_TOKEN }}