name: Functions - main branch

on:
  push:
    branches:
      - 'master'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - name: 'add-entry-function'
            sonar-token: ${{ secrets.ADD_ENTRY_SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd functions/${{ matrix.function.name }}
          mvn -B clean verify

      - name: Publish results to SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd functions/${{ matrix.function.name }}
          mvn -B sonar -Psonar -Dsonar.login=${{ matrix.function.sonar-token }}